# Generated by Django 4.1.4 on 2023-01-03 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("second_name", models.CharField(max_length=200)),
                ("user_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("department", models.CharField(max_length=200)),
                ("password", models.IntegerField()),
                ("password1", models.IntegerField()),
                ("subject", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("second_name", models.CharField(max_length=200)),
                ("user_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("department", models.CharField(max_length=200)),
                ("password", models.IntegerField()),
                ("password1", models.IntegerField()),
                ("year", models.IntegerField()),
                ("status", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("second_name", models.CharField(max_length=200)),
                ("user_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("department", models.CharField(max_length=200)),
                ("password", models.IntegerField()),
                ("password1", models.IntegerField()),
                ("qualification", models.CharField(max_length=200)),
                ("experience", models.IntegerField()),
                ("status", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
