# Generated by Django 4.1.4 on 2023-01-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mycollege", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hod",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="hod",
            name="password1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="password1",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="password1",
            field=models.CharField(max_length=200),
        ),
    ]
